---
- hosts: all

  vars_files:
    - ../config.yml

  pre_tasks:
    - include: tasks/init.yml

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.apache, tags: ['apache'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: paulthed.php, tags: ['php'] }
    - { role: paulthed.php-pecl, tags: ['php'] }
    - { role: paulthed.php-mysql, tags: ['php'] }
    - { role: paulthed.composer, tags: ['composer'] }
    - { role: paulthed.drush, tags: ['drush'] }
    # Roles to be installed conditionally.
    - {
      role: geerlingguy.memcached,
      when: '"memcached" in installed_extras'
    }
    - {
      role: paulthed.php-memcached,
      when: '"memcached" in installed_extras'
    }
    - {
      role: paulthed.php-xdebug,
      when: '"xdebug" in installed_extras'
    }
    - {
      role: paulthed.php-xhprof,
      when: '"xhprof" in installed_extras'
    }
    - {
      role: paulthed.phpmyadmin,
      when: '"phpmyadmin" in installed_extras'
    }
    - {
      role: geerlingguy.daemonize,
      when: '"mailhog" in installed_extras'
    }
    - {
      role: geerlingguy.mailhog,
      when: '"mailhog" in installed_extras'
    }

  tasks:
    - include: tasks/www.yml
    - include: tasks/drupal.yml
